name: flame_raycaster
description: Flame Raycaster Incubator.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.1.0
  tiled: 0.8.0

flutter:
  assets:
    - assets/tiles/raycaster.tmx
    - assets/images/walls.png
    - assets/images/joystick.png

