name: flame_raycaster
description: Flame Raycaster Incubator.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.1.0

flutter:
  assets:
    - data/buttons.json
    - data/level.json
    - data/level2.json
    - img/gui.png
    - img/walls.png
    - img/joystick.png

